#!/usr/bin/env python
"""
=============================================================================
GearGuard Backend - Organization & Users Module Test Suite
=============================================================================

This script tests the Organization and User management endpoints:
- GET  /api/v1/organizations/{id}        - Get organization details
- PUT  /api/v1/organizations/{id}        - Update organization
- GET  /api/v1/organizations/{id}/stats  - Get organization stats
- GET  /api/v1/users                     - List users
- POST /api/v1/users                     - Create new user
- GET  /api/v1/users/{id}                - Get user details
- PUT  /api/v1/users/{id}                - Update user
- PUT  /api/v1/users/{id}/role           - Change user role
- DELETE /api/v1/users/{id}              - Deactivate user

Usage:
    python tests/test_org_users_module.py

Prerequisites:
    - Must run test_auth_module.py first to generate credentials.
"""

import httpx
import json
import uuid
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any, List

# =============================================================================
# Configuration
# =============================================================================

BASE_URL = os.getenv("TEST_BASE_URL", "http://localhost:8000")
API_URL = f"{BASE_URL}/api/v1"
TIMEOUT = 30.0

# Credentials file path (generated by test_auth_module.py)
CREDENTIALS_FILE = Path(__file__).parent / ".test_credentials.json"


# =============================================================================
# Helper Classes
# =============================================================================

class TestResult:
    """Stores test result information."""
    def __init__(self, name: str, passed: bool, message: str = "", response: Optional[Dict] = None):
        self.name = name
        self.passed = passed
        self.message = message
        self.response = response
        self.timestamp = datetime.now().isoformat()

class AuthCredentials:
    """Loads and stores authentication credentials."""
    def __init__(self):
        self.user_id: Optional[str] = None
        self.email: Optional[str] = None
        self.access_token: Optional[str] = None
        self.organization_id: Optional[str] = None
    
    @classmethod
    def load(cls) -> Optional["AuthCredentials"]:
        """Load credentials from file."""
        if not CREDENTIALS_FILE.exists():
            print(f"  ❌ Error: Credentials file not found at {CREDENTIALS_FILE}")
            print("     Please run test_auth_module.py first.")
            return None
        
        try:
            with open(CREDENTIALS_FILE, "r") as f:
                data = json.load(f)
            creds = cls()
            creds.user_id = data.get("user_id")
            creds.email = data.get("email")
            creds.access_token = data.get("access_token")
            creds.organization_id = data.get("organization_id")
            return creds
        except Exception as e:
            print(f"  ❌ Error loading credentials: {str(e)}")
            return None


# =============================================================================
# Test Functions - Organizations
# =============================================================================

def test_get_organization(client: httpx.Client, creds: AuthCredentials) -> TestResult:
    """Test get organization details."""
    print("\n" + "="*60)
    print("  🏢 TEST: Get Organization Details")
    print("="*60)
    
    try:
        response = client.get(f"{API_URL}/organizations/{creds.organization_id}")
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            print(f"  🏢 Name: {data.get('name')}")
            print(f"  🆔 ID: {data.get('id')}")
            print(f"  📍 Address: {data.get('address') or 'N/A'}")
            print(f"  🌍 Website: {data.get('website') or 'N/A'}")
            return TestResult("Get Org", True, "Organization retrieved", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Get Org", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Get Org", False, str(e))


def test_update_organization(client: httpx.Client, creds: AuthCredentials) -> TestResult:
    """Test update organization details."""
    print("\n" + "="*60)
    print("  ✏️  TEST: Update Organization")
    print("="*60)
    
    new_website = f"https://gearguard-{uuid.uuid4().hex[:6]}.com"
    update_data = {
        "website": new_website,
        "address": "123 Tech Park, Innovation Way"
    }
    print(f"  Updating website to: {new_website}")
    
    try:
        response = client.put(
            f"{API_URL}/organizations/{creds.organization_id}", 
            json=update_data
        )
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            print("  ✅ Organization updated successfully!")
            print(f"  🌍 New Website: {data.get('website')}")
            return TestResult("Update Org", True, "Organization updated", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Update Org", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Update Org", False, str(e))


def test_get_org_stats(client: httpx.Client, creds: AuthCredentials) -> TestResult:
    """Test get organization statistics."""
    print("\n" + "="*60)
    print("  📊 TEST: Get Organization Stats")
    print("="*60)
    
    try:
        response = client.get(f"{API_URL}/organizations/{creds.organization_id}/stats")
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            print("  ✅ Stats retrieved successfully!")
            print(f"  👥 Users: {data.get('total_users')}")
            print(f"  📟 Equipment: {data.get('total_equipment')}")
            print(f"  🔧 Work Orders: {data.get('total_work_orders')}")
            return TestResult("Get Org Stats", True, "Stats retrieved", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Get Org Stats", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Get Org Stats", False, str(e))


# =============================================================================
# Test Functions - Users
# =============================================================================

def test_list_users(client: httpx.Client) -> TestResult:
    """Test list users."""
    print("\n" + "="*60)
    print("  👥 TEST: List Users")
    print("="*60)
    
    try:
        response = client.get(f"{API_URL}/users?page=1&page_size=10")
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            items = data.get("items", [])
            total = data.get("total", 0)
            print(f"  ✅ Users retrieved successfully!")
            print(f"  🔢 Total Users: {total}")
            print(f"  📝 Retrieved: {len(items)}")
            if len(items) > 0:
                print(f"  👤 First User: {items[0]['email']} ({items[0]['role']})")
            return TestResult("List Users", True, "Users listed", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("List Users", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("List Users", False, str(e))


def test_create_user(client: httpx.Client) -> tuple[TestResult, Optional[str]]:
    """Test create new user."""
    print("\n" + "="*60)
    print("  ➕ TEST: Create New User")
    print("="*60)
    
    unique_id = uuid.uuid4().hex[:8]
    new_user = {
        "email": f"tech_{unique_id}@gearguard-testing.com",
        "password": f"TechGuard@{unique_id}",
        "first_name": "Tech",
        "last_name": f"Niccian_{unique_id}",
        "role": "technician",
        "phone": "+15559876543"
    }
    print(f"  Creating user: {new_user['email']}")
    
    try:
        response = client.post(f"{API_URL}/users", json=new_user)
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 201:
            user_id = data.get("id")
            print("  ✅ User created successfully!")
            print(f"  👤 User ID: {user_id}")
            print(f"  🎭 Role: {data.get('role')}")
            return TestResult("Create User", True, "User created", data), user_id
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Create User", False, f"Status {response.status_code}"), None
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Create User", False, str(e)), None


def test_update_user(client: httpx.Client, user_id: str) -> TestResult:
    """Test update user details."""
    print("\n" + "="*60)
    print("  ✏️  TEST: Update User")
    print("="*60)
    
    update_data = {
        "first_name": "Technician",
        "phone": "+15550000000"
    }
    
    try:
        response = client.put(f"{API_URL}/users/{user_id}", json=update_data)
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            print("  ✅ User updated successfully!")
            print(f"  📛 Name: {data.get('first_name')} {data.get('last_name')}")
            print(f"  📞 Phone: {data.get('phone')}")
            return TestResult("Update User", True, "User updated", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Update User", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Update User", False, str(e))


def test_change_user_role(client: httpx.Client, user_id: str) -> TestResult:
    """Test change user role."""
    print("\n" + "="*60)
    print("  🎭 TEST: Change User Role")
    print("="*60)
    
    # Change from technician to manager (assuming current user is admin)
    role_data = {"role": "manager"}
    print(f"  Changing role to: {role_data['role']}")
    
    try:
        response = client.put(f"{API_URL}/users/{user_id}/role", json=role_data)
        data = response.json()
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 200:
            print("  ✅ Role updated successfully!")
            print(f"  🎭 New Role: {data.get('role')}")
            return TestResult("Change Role", True, "Role updated", data)
        else:
            print(f"  ❌ Failed: {data}")
            return TestResult("Change Role", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Change Role", False, str(e))


def test_delete_user(client: httpx.Client, user_id: str) -> TestResult:
    """Test delete (deactivate) user."""
    print("\n" + "="*60)
    print("  🗑️  TEST: Delete (Deactivate) User")
    print("="*60)
    
    try:
        response = client.delete(f"{API_URL}/users/{user_id}")
        
        print(f"\n  📊 Status: {response.status_code}")
        
        if response.status_code == 204:
            print("  ✅ User deactivated successfully!")
            
            # Verify deactivation
            verify_response = client.get(f"{API_URL}/users/{user_id}")
            user_data = verify_response.json()
            is_active = user_data.get("is_active")
            print(f"  🔍 Verification (Is Active): {is_active}")
            
            if is_active is False:
                return TestResult("Delete User", True, "User deactivated", None)
            else:
                return TestResult("Delete User", False, "User still active after delete")
        else:
            print(f"  ❌ Failed: {response.text}")
            return TestResult("Delete User", False, f"Status {response.status_code}")
            
    except Exception as e:
        print(f"  ❌ Error: {str(e)}")
        return TestResult("Delete User", False, str(e))


# =============================================================================
# Main Runner
# =============================================================================

def main():
    print("\n")
    print("╔" + "="*60 + "╗")
    print("║" + "  GearGuard - Org & Users Module Test Suite".center(60) + "║")
    print("╚" + "="*60 + "╝")
    print(f"\n  🌐 API URL: {API_URL}")
    print(f"  ⏰ Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Load credentials
    creds = AuthCredentials.load()
    if not creds:
        sys.exit(1)
    
    print(f"  🔑 Authenticated as: {creds.email}")
    print(f"  🏢 Organization ID: {creds.organization_id}")
    
    results: List[TestResult] = []
    
    with httpx.Client(timeout=TIMEOUT) as client:
        # Set auth header
        client.headers.update({"Authorization": f"Bearer {creds.access_token}"})
        
        # --- Organization Tests ---
        results.append(test_get_organization(client, creds))
        results.append(test_update_organization(client, creds))
        results.append(test_get_org_stats(client, creds))
        
        # --- User Tests ---
        results.append(test_list_users(client))
        
        # Create user flow
        create_result, new_user_id = test_create_user(client)
        results.append(create_result)
        
        if new_user_id:
            results.append(test_update_user(client, new_user_id))
            results.append(test_change_user_role(client, new_user_id))
            results.append(test_delete_user(client, new_user_id))
    
    # Summary
    passed = sum(1 for r in results if r.passed)
    total = len(results)
    
    print("\n")
    print("╔" + "="*60 + "╗")
    print("║" + "  TEST SUMMARY".center(60) + "║")
    print("╚" + "="*60 + "╝")
    
    if passed == total:
        print(f"\n  🎉 ALL TESTS PASSED! ({passed}/{total})")
    else:
        print(f"\n  ❌ TESTS FAILED: {passed}/{total}")
        
    print("\n" + "="*62 + "\n")
    
    if passed < total:
        sys.exit(1)

if __name__ == "__main__":
    main()
