"""
GearGuard Backend - Core Module
Security, permissions, and exception handling.
"""
from .security import (
    verify_password,
    get_password_hash,
    validate_password_strength,
    create_access_token,
    create_refresh_token,
    create_token_pair,
    decode_access_token,
    decode_refresh_token,
    generate_id,
    hash_token,
    generate_reset_token,
    generate_verification_token,
    utcnow_iso,
    TokenPayload,
    RefreshTokenPayload,
    TokenPair,
)

from .permissions import (
    Permission,
    Role,
    ROLE_PERMISSIONS,
    has_permission,
    has_any_permission,
    has_all_permissions,
    get_role_permissions,
    can_manage_role,
    require_permission,
    require_any_permission,
    require_role,
    require_same_org,
)

from .exceptions import (
    GearGuardException,
    AuthenticationError,
    InvalidCredentialsError,
    TokenExpiredError,
    InvalidTokenError,
    SessionExpiredError,
    AccountDisabledError,
    EmailNotVerifiedError,
    AuthorizationError,
    PermissionDeniedError,
    ResourceAccessDeniedError,
    ResourceError,
    ResourceNotFoundError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ValidationError,
    InvalidInputError,
    BusinessLogicError,
    WorkOrderError,
    InventoryError,
    InsufficientStockError,
    to_http_exception,
)

__all__ = [
    # Security
    "verify_password",
    "get_password_hash",
    "validate_password_strength",
    "create_access_token",
    "create_refresh_token",
    "create_token_pair",
    "decode_access_token",
    "decode_refresh_token",
    "generate_id",
    "hash_token",
    "generate_reset_token",
    "generate_verification_token",
    "utcnow_iso",
    "TokenPayload",
    "RefreshTokenPayload",
    "TokenPair",
    
    # Permissions
    "Permission",
    "Role",
    "ROLE_PERMISSIONS",
    "has_permission",
    "has_any_permission",
    "has_all_permissions",
    "get_role_permissions",
    "can_manage_role",
    "require_permission",
    "require_any_permission",
    "require_role",
    "require_same_org",
    
    # Exceptions
    "GearGuardException",
    "AuthenticationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "InvalidTokenError",
    "SessionExpiredError",
    "AccountDisabledError",
    "EmailNotVerifiedError",
    "AuthorizationError",
    "PermissionDeniedError",
    "ResourceAccessDeniedError",
    "ResourceError",
    "ResourceNotFoundError",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "ValidationError",
    "InvalidInputError",
    "BusinessLogicError",
    "WorkOrderError",
    "InventoryError",
    "InsufficientStockError",
    "to_http_exception",
]
